id: hreflang_settings
label: Hreflang settings
migration_tags:
  - Drupal 7
  - Configuration
source:
  plugin: variable
  variables:
    - hreflang_x_default
  source_module: hreflang
process:
  x_default: hreflang_x_default
destination:
  plugin: config
  config_name: hreflang.settings
